#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Adrian Hooper"
email = "git@ca.hooper.co.uk"

[ui]
diff-editor = "vscode"
merge-editor = "vscode"

[remotes.origin]
auto-track-created-bookmarks = "*"
